# src/document_processing/processor.py
"""
Document Processing Pipeline
Handles PDF and Excel document ingestion, extraction, and chunking
Includes OCR fallback for scanned documents using Tesseract
"""

# Import necessary libraries
import fitz  # PyMuPDF for PDF text extraction
import pdfplumber  # For table extraction from PDFs
import pandas as pd  # For data manipulation and Excel processing
from typing import List, Dict, Tuple, Optional, Any  # For type hints
from dataclasses import dataclass  # For creating data classes
import re  # For regular expressions (text cleaning)
from pathlib import Path  # For path manipulation
import logging  # For logging functionality
import gc  # Manual garbage collection between heavy PDF pages (memory hygiene)
import os  # CPU detection for parallel workers
import multiprocessing as mp  # Process-based parallelism for pdfplumber (GIL-bound)
from concurrent.futures import (
    ProcessPoolExecutor,
    ThreadPoolExecutor,
    as_completed,
)
from PIL import Image  # For image processing (OCR)
import io  # For byte stream handling

# Try to import pytesseract for OCR functionality
try:
    import pytesseract  # OCR library
    OCR_AVAILABLE = True  # Flag indicating OCR is available
except ImportError:
    OCR_AVAILABLE = False  # Flag indicating OCR is not available
    
# Configure logging
logging.basicConfig(level=logging.INFO)  # Set default logging level to INFO
logger = logging.getLogger(__name__)  # Create logger instance for this module


# Data class to represent a document chunk
@dataclass
class DocumentChunk:
    """
    Represents a chunk of document content with metadata
    
    Attributes:
        content: The actual text content
        metadata: Dictionary containing source info (doc_name, page, section, etc.)
        chunk_id: Unique identifier for the chunk
        temporal_entities: List of temporal entities found in this chunk
        valid_from: Start date of validity period (ISO format: YYYY-MM-DD)
        valid_to: End date of validity period (ISO format: YYYY-MM-DD)
    """
    content: str  # The text content of the chunk
    metadata: Dict[str, Any]  # Metadata about the chunk (source, page, etc.)
    chunk_id: str  # Unique identifier for the chunk
    temporal_entities: Optional[List] = None  # List of TemporalEntity objects
    valid_from: Optional[str] = None  # Validity start date
    valid_to: Optional[str] = None  # Validity end date
    
    # String representation for debugging
    def __repr__(self):
        temporal_info = f", temporal={len(self.temporal_entities) if self.temporal_entities else 0}" if self.temporal_entities else ""
        return f"Chunk({self.chunk_id}, len={len(self.content)}, page={self.metadata.get('page')}{temporal_info})"


# Data class to represent an image chunk from documents (for multimodal RAG)
@dataclass
class ImageChunk:
    """
    Represents an extracted image from a document with metadata
    Used for multimodal RAG with vision models
    
    Attributes:
        image: PIL Image object
        image_bytes: Raw bytes of the image (for API calls)
        metadata: Dictionary containing source info (doc_name, page, etc.)
        chunk_id: Unique identifier for the image chunk
        description: Optional text description of the image content
    """
    image: Image.Image  # PIL Image object
    image_bytes: bytes  # Raw image bytes for API calls
    metadata: Dict[str, Any]  # Metadata about the image source
    chunk_id: str  # Unique identifier
    description: str = ""  # Optional description (can be generated by vision model)
    
    # String representation for debugging
    def __repr__(self):
        return f"ImageChunk({self.chunk_id}, page={self.metadata.get('page')}, size={self.image.size if self.image else 'N/A'})"


# ──────────────────────────────────────────────────────────────────────────────
# Module-level helpers for PARALLEL PDF processing.
#
# These live at module level (not as class methods) for two reasons:
#   1. ProcessPoolExecutor with the 'spawn' start method needs picklable,
#      importable callables — bound methods on a class with heavy state
#      (Tesseract config, etc.) don't pickle cleanly.
#   2. Worker processes re-import the module fresh, so we want zero
#      dependency on instance state.
#
# Quality is preserved: workers use the *exact* same pdfplumber call
# (`page.extract_tables()` with default settings) and the same text formatting
# logic as the serial path.
# ──────────────────────────────────────────────────────────────────────────────

def _table_to_text_pure(df: "pd.DataFrame") -> str:
    """Pure-function version of PDFProcessor._table_to_text.

    Same output, no `self` — safe to call from worker processes.
    """
    lines: List[str] = []
    headers = [str(col) for col in df.columns if col is not None]
    if headers:
        lines.append("Table: " + ", ".join(headers))
    for _, row in df.iterrows():
        row_parts = []
        for col, val in zip(df.columns, row.values):
            if val is not None and str(val).strip():
                row_parts.append(f"{col}: {val}")
        if row_parts:
            lines.append("; ".join(row_parts))
    return "\n".join(lines)


def _extract_tables_for_page_range(
    pdf_path: str,
    page_indices: List[int],
) -> List[Dict[str, Any]]:
    """Worker: extract tables from a contiguous range of 1-indexed pages.

    Runs in a separate process. Opens its own pdfplumber handle, processes
    only the given page indices, then returns a list of table dicts. We
    flush each page's pdfplumber cache after use so the worker's RSS stays
    flat regardless of chunk size.
    """
    # Fresh imports because spawned workers don't inherit parent state
    import logging as _logging
    import pdfplumber as _pp
    import pandas as _pd

    _wlog = _logging.getLogger("processor.worker")
    results: List[Dict[str, Any]] = []
    if not page_indices:
        return results

    doc_stem = Path(pdf_path).stem
    try:
        with _pp.open(pdf_path) as pdf:
            n_pages = len(pdf.pages)
            for page_num in page_indices:
                if page_num < 1 or page_num > n_pages:
                    continue
                try:
                    page = pdf.pages[page_num - 1]
                    try:
                        tables = page.extract_tables()
                    except Exception as pe:  # noqa: BLE001
                        _wlog.warning(
                            "Worker: extract_tables failed on page %d: %s",
                            page_num, pe,
                        )
                        tables = []

                    for table_idx, table in enumerate(tables):
                        if not (table and len(table) > 1):
                            continue
                        try:
                            headers = [
                                str(h) if h else f"Col{i}"
                                for i, h in enumerate(table[0])
                            ]
                            df = _pd.DataFrame(table[1:], columns=headers)
                            table_text = _table_to_text_pure(df)
                            del df
                            if table_text and len(table_text) > 20:
                                results.append({
                                    'page_num': page_num,
                                    'table_idx': table_idx,
                                    'text': table_text,
                                    'doc_name': doc_stem,
                                })
                        except Exception as te:  # noqa: BLE001
                            _wlog.warning(
                                "Worker: table format failed on page %d: %s",
                                page_num, te,
                            )

                    try:
                        page.flush_cache()
                    except AttributeError:
                        pass
                except Exception as page_err:  # noqa: BLE001
                    _wlog.warning(
                        "Worker: page %d crashed: %s", page_num, page_err
                    )
        return results
    except Exception as e:  # noqa: BLE001
        _wlog.error(
            "Worker for %s pages %s..%s aborted: %s",
            pdf_path,
            page_indices[0],
            page_indices[-1],
            e,
        )
        return results


def _ocr_image_bytes(png_bytes: bytes) -> str:
    """Worker: OCR a rendered page image (PNG bytes) with Tesseract.

    Tesseract is invoked via subprocess by pytesseract, which releases the
    GIL — so a ThreadPoolExecutor in the parent process gives us real
    parallel OCR without the spawn-process overhead.
    """
    try:
        import pytesseract as _pyt
        from PIL import Image as _Image
        img = _Image.open(io.BytesIO(png_bytes))
        try:
            return _pyt.image_to_string(img)
        finally:
            img.close()
    except Exception as e:  # noqa: BLE001
        logger.warning(f"OCR worker failed: {e}")
        return ""


def _decide_pdf_workers(num_pages: int, cap: int = 8) -> int:
    """Pick a sensible worker count for a PDF of `num_pages` pages.

    - Respects cgroup CPU affinity in Docker (Linux) via sched_getaffinity.
    - Caps at `cap` to avoid pickling/IPC overhead dwarfing real work.
    - Never spawns more workers than pages/4 (each worker should have real work).
    """
    try:
        cpu = len(os.sched_getaffinity(0))  # respects Docker cgroup CPU limits
    except (AttributeError, OSError):
        cpu = os.cpu_count() or 2
    return max(1, min(cap, cpu - 1, max(1, num_pages // 4)))


# Class for processing PDF documents
class PDFProcessor:
    """
    Handles PDF document processing including text and table extraction
    Uses PyMuPDF for text, pdfplumber for tables, and Tesseract OCR for scanned docs
    """
    
    # Initialize PDF processor
    def __init__(self, preserve_layout: bool = True, use_ocr: bool = True):
        """
        Initialize PDF processor
        
        Args:
            preserve_layout: Whether to maintain document layout during extraction
            use_ocr: Whether to use OCR as fallback for scanned documents
        """
        self.preserve_layout = preserve_layout  # Layout preservation flag
        self.use_ocr = use_ocr and OCR_AVAILABLE  # OCR flag (only True if both requested and available)
        
        # Warn if OCR requested but not available
        if use_ocr and not OCR_AVAILABLE:
            logger.warning("OCR requested but pytesseract not installed. Install with: pip install pytesseract")
    
    # Method to extract text from PDF
    def extract_text(self, pdf_path: str) -> List[Dict]:
        """
        Extract text from PDF with page-level metadata.
        Falls back to OCR for pages with insufficient text.

        Pipeline:
          Pass 1 (serial, fast): PyMuPDF text extraction. For pages that need
            OCR, render to PNG bytes immediately (PyMuPDF page objects are not
            thread-safe; the rendered bytes ARE).
          Pass 2 (parallel threads, only if any pages need OCR): run Tesseract
            on the rendered images. Tesseract releases the GIL via subprocess,
            so threads give real parallelism without spawn overhead.

        OCR settings, DPI (2x zoom), and Tesseract config are unchanged — the
        textual output is identical to the old serial path; it just arrives
        ~Nx faster on scan-heavy PDFs.
        """
        logger.info(f"Processing PDF: {pdf_path}")
        pages_content: List[Dict] = []

        try:
            # Pass 1 — direct PyMuPDF text + render OCR-needed pages
            ocr_jobs: List[Tuple[int, bytes]] = []  # (page_num, png_bytes)
            page_results: Dict[int, str] = {}  # page_num -> text (final or temp)
            with fitz.open(pdf_path) as doc:
                for page_num, page in enumerate(doc, start=1):
                    text = page.get_text("text")
                    if self.use_ocr and (not text or len(text.strip()) < 20):
                        logger.info(
                            f"Page {page_num}: Low text content, queueing for OCR..."
                        )
                        if not OCR_AVAILABLE:
                            page_results[page_num] = ""
                            continue
                        # Render synchronously (PyMuPDF Page is not thread-safe);
                        # the resulting bytes are safe to pass to OCR threads.
                        pix = None
                        try:
                            mat = fitz.Matrix(2.0, 2.0)
                            pix = page.get_pixmap(matrix=mat)
                            png_bytes = pix.tobytes("png")
                            ocr_jobs.append((page_num, png_bytes))
                            page_results[page_num] = ""  # placeholder, filled in pass 2
                        except Exception as render_err:  # noqa: BLE001
                            logger.warning(
                                f"Page {page_num}: render-for-OCR failed: {render_err}"
                            )
                            page_results[page_num] = ""
                        finally:
                            try:
                                if pix is not None and hasattr(pix, "close"):
                                    pix.close()
                            except Exception:  # noqa: BLE001
                                pass
                    else:
                        page_results[page_num] = text

            # Pass 2 — parallel OCR (only if any pages need it)
            if ocr_jobs:
                ocr_workers = min(4, max(1, len(ocr_jobs)))
                logger.info(
                    f"Running OCR on {len(ocr_jobs)} page(s) with {ocr_workers} thread(s)..."
                )
                with ThreadPoolExecutor(max_workers=ocr_workers) as ex:
                    future_to_page = {
                        ex.submit(_ocr_image_bytes, png): pn
                        for pn, png in ocr_jobs
                    }
                    for fut in as_completed(future_to_page):
                        pn = future_to_page[fut]
                        try:
                            ocr_text = fut.result()
                        except Exception as ocr_err:  # noqa: BLE001
                            logger.warning(f"OCR failed on page {pn}: {ocr_err}")
                            ocr_text = ""
                        page_results[pn] = ocr_text
                        logger.info(
                            f"  ▶ OCR done [page {pn}]: {len(ocr_text)} chars"
                        )

            # Assemble in original page order
            for page_num in sorted(page_results.keys()):
                cleaned_text = self._clean_text(page_results[page_num])
                if cleaned_text:
                    pages_content.append({
                        'page_num': page_num,
                        'text': cleaned_text,
                        'doc_name': Path(pdf_path).stem,
                    })

            logger.info(f"Extracted {len(pages_content)} pages from {pdf_path}")
            return pages_content

        except Exception as e:
            logger.error(f"Error processing {pdf_path}: {str(e)}")
            raise
    
    # Private method for OCR processing
    def _ocr_page(self, page) -> str:
        """
        Perform OCR on a page using Tesseract
        
        Args:
            page: PyMuPDF page object
            
        Returns:
            Extracted text from OCR
        """
        # Check if OCR is available
        if not OCR_AVAILABLE:
            return ""  # Return empty string if OCR not available
        
        pix = None
        img = None
        try:
            mat = fitz.Matrix(2.0, 2.0)
            pix = page.get_pixmap(matrix=mat)
            img_data = pix.tobytes("png")
            img = Image.open(io.BytesIO(img_data))
            text = pytesseract.image_to_string(img)
            logger.info(f"OCR extracted {len(text)} characters")
            return text

        except Exception as e:
            logger.warning(f"OCR failed: {str(e)}")
            return ""
        finally:
            # Release the pixmap's C buffer and PIL image promptly. This matters
            # when many pages need OCR back-to-back (e.g. scanned banking PDFs).
            try:
                if img is not None:
                    img.close()
            except Exception:  # noqa: BLE001
                pass
            try:
                if pix is not None:
                    # PyMuPDF Pixmap exposes both .close() (newer) and falls
                    # back to del to drop the underlying C resource.
                    if hasattr(pix, "close"):
                        pix.close()
            except Exception:  # noqa: BLE001
                pass
    
    # Method to extract images from PDF (for multimodal RAG)
    def extract_images(self, pdf_path: str, min_size: int = 100, output_dir: str = None) -> List['ImageChunk']:
        """
        Extract images from PDF for multimodal analysis
        Captures charts, graphs, and figures from financial documents
        
        Args:
            pdf_path: Path to PDF file
            min_size: Minimum pixel dimension to filter out tiny images
            output_dir: Optional directory to save extracted images
            
        Returns:
            List of ImageChunk objects
        """
        logger.info(f"Extracting images from: {pdf_path}")
        image_chunks = []  # List to store extracted image chunks
        
        try:
            # Open PDF using PyMuPDF
            with fitz.open(pdf_path) as doc:
                doc_name = Path(pdf_path).stem  # Document name without extension
                
                # Process each page
                for page_num, page in enumerate(doc, start=1):
                    # Get list of images on the page
                    image_list = page.get_images(full=True)
                    
                    for img_idx, img_info in enumerate(image_list):
                        try:
                            # Extract image reference number
                            xref = img_info[0]
                            
                            # Extract base image data
                            base_image = doc.extract_image(xref)
                            image_bytes = base_image["image"]
                            image_ext = base_image["ext"]
                            
                            # Convert to PIL Image
                            pil_image = Image.open(io.BytesIO(image_bytes))
                            
                            # Filter out small images (icons, bullets, etc.)
                            width, height = pil_image.size
                            if width < min_size or height < min_size:
                                continue
                            
                            # Convert to RGB if necessary (for consistency)
                            if pil_image.mode != 'RGB':
                                pil_image = pil_image.convert('RGB')
                            
                            # Re-encode as PNG for consistent format
                            img_buffer = io.BytesIO()
                            pil_image.save(img_buffer, format='PNG')
                            img_bytes = img_buffer.getvalue()
                            
                            # Create unique chunk ID
                            chunk_id = f"{doc_name}_p{page_num}_img{img_idx}"
                            
                            # Create ImageChunk
                            image_chunk = ImageChunk(
                                image=pil_image,
                                image_bytes=img_bytes,
                                metadata={
                                    'doc_name': doc_name,
                                    'page': page_num,
                                    'image_index': img_idx,
                                    'width': width,
                                    'height': height,
                                    'source_type': 'pdf_image'
                                },
                                chunk_id=chunk_id
                            )
                            image_chunks.append(image_chunk)
                            
                            # Optionally save to disk
                            if output_dir:
                                output_path = Path(output_dir)
                                output_path.mkdir(parents=True, exist_ok=True)
                                save_path = output_path / f"{chunk_id}.png"
                                pil_image.save(save_path)
                                logger.debug(f"Saved image: {save_path}")
                                
                        except Exception as img_error:
                            logger.warning(f"Failed to extract image {img_idx} from page {page_num}: {img_error}")
                            continue
                    
                    # Also capture rendered page as image for charts that aren't embedded images
                    # This captures vector graphics, charts drawn with lines, etc.
                    if page_num <= 10:  # Limit to first 10 pages for page renders
                        try:
                            # Render page at medium resolution
                            mat = fitz.Matrix(1.5, 1.5)  # 1.5x zoom
                            pix = page.get_pixmap(matrix=mat)
                            
                            # Only save if page has visual content beyond text
                            if len(image_list) > 0 or self._page_has_graphics(page):
                                img_data = pix.tobytes("png")
                                page_img = Image.open(io.BytesIO(img_data))
                                
                                # Convert to RGB
                                if page_img.mode != 'RGB':
                                    page_img = page_img.convert('RGB')
                                
                                chunk_id = f"{doc_name}_p{page_num}_fullpage"
                                
                                image_chunk = ImageChunk(
                                    image=page_img,
                                    image_bytes=img_data,
                                    metadata={
                                        'doc_name': doc_name,
                                        'page': page_num,
                                        'image_index': -1,  # -1 indicates full page render
                                        'width': pix.width,
                                        'height': pix.height,
                                        'source_type': 'pdf_page_render'
                                    },
                                    chunk_id=chunk_id
                                )
                                image_chunks.append(image_chunk)
                        except Exception as render_error:
                            logger.warning(f"Failed to render page {page_num}: {render_error}")
            
            logger.info(f"Extracted {len(image_chunks)} images from {pdf_path}")
            return image_chunks
            
        except Exception as e:
            logger.error(f"Error extracting images from {pdf_path}: {str(e)}")
            return []
    
    # Helper method to check if page has vector graphics
    def _page_has_graphics(self, page) -> bool:
        """Check if page has vector graphics (charts, diagrams, etc.)"""
        try:
            # Get page drawings (paths, lines, rectangles, etc.)
            drawings = page.get_drawings()
            # If there are more than 10 drawing elements, likely has charts/graphics
            return len(drawings) > 10
        except:
            return False
    
    # Method to extract tables from PDF
    def extract_tables(
        self,
        pdf_path: str,
        max_pages: Optional[int] = None,
        progress_every: int = 10,
        num_workers: Optional[int] = None,
        parallel_threshold: int = 16,
    ) -> List[Dict]:
        """
        Extract tables from PDF using pdfplumber.

        For long documents the work is split across multiple processes; for
        short ones we stay serial to avoid spawn overhead. Output is identical
        in either path — same pdfplumber call, same formatting — so retrieval
        quality is unchanged.

        Args:
            pdf_path: Path to PDF file.
            max_pages: If not None, stop after this many pages. Useful for
                pathologically large PDFs.
            progress_every: Log a progress line every N pages (serial path
                only; parallel path logs per worker).
            num_workers: Override worker count. If None, auto-tuned from
                CPU affinity and page count.
            parallel_threshold: PDFs with fewer pages than this go through
                the serial path (spawn overhead would dominate).

        Returns:
            List of dictionaries containing table data and metadata, sorted
            by (page_num, table_idx).
        """
        logger.info(f"Extracting tables from: {pdf_path}")

        try:
            with pdfplumber.open(pdf_path) as pdf:
                total_pages = len(pdf.pages)
        except Exception as e:  # noqa: BLE001
            logger.error(f"Could not open {pdf_path} for table extraction: {e}")
            return []

        effective_limit = (
            min(total_pages, max_pages) if max_pages is not None else total_pages
        )
        skipped_due_to_limit = max(0, total_pages - effective_limit)
        if skipped_due_to_limit:
            logger.warning(
                "PDF has %d pages but max_pages=%d; skipping table "
                "extraction on the trailing %d pages.",
                total_pages, max_pages, skipped_due_to_limit,
            )

        if effective_limit < parallel_threshold:
            return self._extract_tables_serial(
                pdf_path, effective_limit, progress_every, skipped_due_to_limit,
            )
        return self._extract_tables_parallel(
            pdf_path, effective_limit, num_workers, skipped_due_to_limit,
        )

    def _extract_tables_serial(
        self,
        pdf_path: str,
        effective_limit: int,
        progress_every: int,
        skipped_due_to_limit: int,
    ) -> List[Dict]:
        """Serial table extraction — used for short PDFs."""
        tables_data: List[Dict] = []
        try:
            with pdfplumber.open(pdf_path) as pdf:
                for page_num, page in enumerate(pdf.pages, start=1):
                    if page_num > effective_limit:
                        break
                    try:
                        tables = page.extract_tables()
                    except Exception as pe:  # noqa: BLE001
                        logger.warning(
                            "Table extraction failed on page %d: %s", page_num, pe
                        )
                        tables = []

                    for table_idx, table in enumerate(tables):
                        if not (table and len(table) > 1):
                            continue
                        try:
                            headers = [
                                str(h) if h else f"Col{i}"
                                for i, h in enumerate(table[0])
                            ]
                            df = pd.DataFrame(table[1:], columns=headers)
                            table_text = self._table_to_text(df)
                            del df
                            if table_text and len(table_text) > 20:
                                tables_data.append({
                                    'page_num': page_num,
                                    'table_idx': table_idx,
                                    'text': table_text,
                                    'doc_name': Path(pdf_path).stem,
                                })
                        except Exception as te:  # noqa: BLE001
                            logger.warning(
                                "Error processing table on page %d: %s",
                                page_num, te,
                            )

                    try:
                        page.flush_cache()
                    except AttributeError:
                        getattr(page, "close", lambda: None)()

                    if page_num % progress_every == 0 or page_num == effective_limit:
                        logger.info(
                            "  ▶ table extraction (serial): %d / %d pages, "
                            "%d tables so far",
                            page_num, effective_limit, len(tables_data),
                        )
                        gc.collect()

            logger.info(
                "Extracted %d tables from %s [serial, pages skipped: %d]",
                len(tables_data), pdf_path, skipped_due_to_limit,
            )
            return tables_data
        except Exception as e:  # noqa: BLE001
            logger.error(f"Error extracting tables from {pdf_path}: {str(e)}")
            return tables_data

    def _extract_tables_parallel(
        self,
        pdf_path: str,
        effective_limit: int,
        num_workers: Optional[int],
        skipped_due_to_limit: int,
    ) -> List[Dict]:
        """Parallel table extraction — splits pages across processes.

        Each worker opens its own pdfplumber handle and processes a contiguous
        chunk of pages. Results are merged and re-sorted to match the serial
        output order.
        """
        workers = num_workers or _decide_pdf_workers(effective_limit)
        all_pages = list(range(1, effective_limit + 1))
        chunk_size = max(1, (len(all_pages) + workers - 1) // workers)
        chunks = [
            all_pages[i:i + chunk_size]
            for i in range(0, len(all_pages), chunk_size)
        ]
        logger.info(
            "Parallel table extraction: %d pages → %d workers, ~%d pages each",
            effective_limit, len(chunks), chunk_size,
        )

        all_results: List[Dict] = []
        # 'spawn' is used because the parent process has already imported heavy
        # libraries (torch, transformers, streamlit). 'fork' would copy all of
        # that and could deadlock on threading primitives held by them.
        ctx = mp.get_context("spawn")
        try:
            with ProcessPoolExecutor(max_workers=workers, mp_context=ctx) as ex:
                future_to_chunk = {
                    ex.submit(_extract_tables_for_page_range, pdf_path, chunk): chunk
                    for chunk in chunks
                }
                completed = 0
                for fut in as_completed(future_to_chunk):
                    chunk = future_to_chunk[fut]
                    try:
                        chunk_results = fut.result()
                        all_results.extend(chunk_results)
                        completed += 1
                        logger.info(
                            "  ▶ worker done [pages %d–%d]: %d tables found "
                            "(%d / %d workers complete)",
                            chunk[0], chunk[-1], len(chunk_results),
                            completed, len(chunks),
                        )
                    except Exception as e:  # noqa: BLE001
                        logger.error(
                            "Worker for pages %d–%d failed: %s",
                            chunk[0], chunk[-1], e,
                        )
        except Exception as e:  # noqa: BLE001
            # Hard fallback: if the process pool itself blows up (e.g. spawn
            # forbidden in some sandboxed environment), fall back to serial
            # so the user still gets results, just slower.
            logger.error(
                "Parallel table extraction failed (%s); falling back to serial.",
                e,
            )
            return self._extract_tables_serial(
                pdf_path, effective_limit, 10, skipped_due_to_limit,
            )

        all_results.sort(key=lambda r: (r['page_num'], r['table_idx']))
        logger.info(
            "Extracted %d tables from %s [parallel x%d, pages skipped: %d]",
            len(all_results), pdf_path, workers, skipped_due_to_limit,
        )
        gc.collect()
        return all_results
    
    # Helper method to clean text
    def _clean_text(self, text: str) -> str:
        """Clean and normalize extracted text while preserving important content"""
        if not text:  # Check for empty text
            return ""  # Return empty string
        # Remove excessive whitespace but preserve single spaces
        text = re.sub(r'\n+', ' ', text)  # Replace newlines with spaces
        text = re.sub(r'\t+', ' ', text)  # Replace tabs with spaces
        text = re.sub(r' +', ' ', text)   # Collapse multiple spaces to single space
        # Remove control characters only (preserve most special characters)
        text = re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]', '', text)  # Remove control chars
        return text.strip()  # Return cleaned and trimmed text
    
    # Helper method to convert DataFrame to text
    def _table_to_text(self, df: pd.DataFrame) -> str:
        """
        Convert DataFrame to formatted text representation
        Useful for embedding and retrieval
        """
        lines = []  # List to store text lines
        
        # Add table headers
        headers = [str(col) for col in df.columns if col is not None]
        if headers:
            lines.append("Table: " + ", ".join(headers))  # Add header line
        
        # Add rows as natural text
        for idx, row in df.iterrows():
            row_parts = []  # List for row parts
            for i, (col, val) in enumerate(zip(df.columns, row.values)):
                # Only include non-empty values
                if val is not None and str(val).strip():
                    row_parts.append(f"{col}: {val}")  # Format as "column: value"
            # Add row if it has content
            if row_parts:
                lines.append("; ".join(row_parts))
        
        return "\n".join(lines)  # Join all lines with newlines


# Class for processing Excel documents
class ExcelProcessor:
    """Handles Excel/CSV document processing"""
    
    # Method to process Excel files
    def process_excel(self, file_path: str) -> List[Dict]:
        """
        Process Excel file and extract all sheets
        
        Args:
            file_path: Path to Excel file
            
        Returns:
            List of dictionaries containing sheet data
        """
        logger.info(f"Processing Excel: {file_path}")  # Log start of processing
        sheets_data = []  # List to store sheet data
        
        try:
            # Read all sheets from Excel file
            excel_file = pd.ExcelFile(file_path)
            
            # Process each sheet
            for sheet_name in excel_file.sheet_names:
                # Read sheet into DataFrame
                df = pd.read_excel(file_path, sheet_name=sheet_name)
                
                # Convert DataFrame to string representation
                sheet_text = df.to_string()
                # Only add sheets with meaningful content
                if sheet_text and len(sheet_text.strip()) > 20:
                    sheets_data.append({
                        'sheet_name': sheet_name,  # Sheet name
                        'dataframe': df,  # DataFrame representation
                        'text': sheet_text,  # Text representation
                        'doc_name': Path(file_path).stem,  # Document name
                        'page_num': 0  # Excel doesn't have pages, use 0
                    })
            
            # Log completion
            logger.info(f"Processed {len(sheets_data)} sheets from {file_path}")
            return sheets_data  # Return list of sheet data
            
        except Exception as e:
            logger.error(f"Error processing {file_path}: {str(e)}")  # Log error
            raise  # Re-raise exception


# Class for intelligent document chunking
class DocumentChunker:
    """
    Intelligent chunking strategy for financial documents
    Implements semantic chunking with overlap and temporal extraction
    """
    
    # Initialize chunker with parameters
    def __init__(self, chunk_size: int = 512, overlap: int = 50, min_chunk_length: int = 30, 
                 extract_temporal: bool = True):
        """
        Initialize chunker
        
        Args:
            chunk_size: Maximum tokens per chunk
            overlap: Number of overlapping tokens between chunks
            min_chunk_length: Minimum character length for a chunk
            extract_temporal: Whether to extract temporal entities from chunks
        """
        self.chunk_size = chunk_size  # Maximum size of each chunk
        self.overlap = overlap  # Overlap between consecutive chunks
        self.min_chunk_length = min_chunk_length  # Minimum acceptable chunk length
        self.extract_temporal = extract_temporal  # Whether to extract temporal entities
        
        # Initialize temporal extractor if needed
        self.temporal_extractor = None
        if self.extract_temporal:
            try:
                # Import here to avoid circular dependency
                from temporal import TemporalEntityExtractor
                self.temporal_extractor = TemporalEntityExtractor(use_spacy=False)
                logger.info("✅ Temporal extraction enabled for chunking")
            except ImportError as e:
                logger.warning(f"Could not import temporal extractor: {e}")
                self.extract_temporal = False
    
    # Method to chunk documents
    def chunk_documents(self, documents: List[Dict], doc_filename: str = None) -> List[DocumentChunk]:
        """
        Chunk documents into smaller pieces with metadata preservation
        Extracts temporal entities from each chunk
        
        Args:
            documents: List of document dictionaries from processors
            doc_filename: Original document filename (for temporal extraction)
            
        Returns:
            List of DocumentChunk objects with temporal metadata
        """
        all_chunks = []  # List to store all chunks
        
        # Extract document-level temporal metadata from filename if available
        doc_temporal_metadata = None
        if self.extract_temporal and self.temporal_extractor and doc_filename:
            try:
                # Get full document text for temporal extraction
                full_text = " ".join([doc.get('text', '') for doc in documents])
                doc_temporal_metadata = self.temporal_extractor.extract_document_metadata(
                    text=full_text[:5000],  # Use first 5000 chars for efficiency
                    filename=doc_filename
                )
                logger.info(f"📅 Extracted document temporal metadata: valid_from={doc_temporal_metadata.valid_from}, valid_to={doc_temporal_metadata.valid_to}")
            except Exception as e:
                logger.warning(f"Error extracting document temporal metadata: {e}")
        
        # Process each document
        for doc in documents:
            text = doc.get('text', '')  # Extract text content
            doc_name = doc.get('doc_name', 'unknown')  # Extract document name
            page_num = doc.get('page_num', 0)  # Extract page number
            
            # Skip documents with insufficient content
            if not text or len(text.strip()) < self.min_chunk_length:
                logger.debug(f"Skipping document with insufficient content: {doc_name}")
                continue
            
            # Apply semantic chunking to the text
            chunks = self._semantic_chunk(text)
            
            # Create DocumentChunk objects for each chunk
            for idx, chunk_text in enumerate(chunks):
                # Only create chunks with sufficient content
                if chunk_text and len(chunk_text.strip()) >= self.min_chunk_length:
                    # Extract temporal entities from this chunk
                    chunk_temporal_entities = None
                    if self.extract_temporal and self.temporal_extractor:
                        try:
                            chunk_temporal_entities = self.temporal_extractor.extract_from_text(chunk_text)
                        except Exception as e:
                            logger.debug(f"Error extracting temporal entities from chunk: {e}")
                    
                    # Determine chunk validity period
                    # Use document-level validity if available, otherwise try to infer from chunk
                    valid_from = None
                    valid_to = None
                    if doc_temporal_metadata:
                        valid_from = doc_temporal_metadata.valid_from
                        valid_to = doc_temporal_metadata.valid_to
                    elif chunk_temporal_entities:
                        # Try to find a date range or quarter in the chunk
                        for entity in chunk_temporal_entities:
                            if entity.start_date and entity.end_date:
                                valid_from = entity.start_date
                                valid_to = entity.end_date
                                break
                    
                    chunk = DocumentChunk(
                        content=chunk_text,  # Chunk text content
                        metadata={
                            'doc_name': doc_name,  # Source document name
                            'page': page_num,  # Page number
                            'chunk_index': idx,  # Index within document
                            'source_type': 'pdf' if page_num > 0 else 'excel',  # Document type
                            'has_temporal_entities': len(chunk_temporal_entities) > 0 if chunk_temporal_entities else False
                        },
                        chunk_id=f"{doc_name}_p{page_num}_c{idx}",  # Unique ID
                        temporal_entities=chunk_temporal_entities,  # Temporal entities
                        valid_from=valid_from,  # Validity start
                        valid_to=valid_to  # Validity end
                    )
                    all_chunks.append(chunk)  # Add to list
        
        # Log completion with temporal stats
        temporal_chunks = sum(1 for c in all_chunks if c.temporal_entities and len(c.temporal_entities) > 0)
        logger.info(f"Created {len(all_chunks)} chunks from {len(documents)} documents ({temporal_chunks} with temporal entities)")
        return all_chunks  # Return list of chunks
    
    # Private method for semantic chunking
    def _semantic_chunk(self, text: str) -> List[str]:
        """
        Implement semantic chunking respecting sentence boundaries
        
        Args:
            text: Text to chunk
            
        Returns:
            List of text chunks
        """
        # Handle empty or very short text
        if not text or len(text.strip()) < self.min_chunk_length:
            # Return text if it exists, otherwise empty list
            return [text.strip()] if text and len(text.strip()) > 0 else []
        
        # Try to split on sentence boundaries using regex
        # Split on period, exclamation mark, or question mark followed by whitespace
        sentences = re.split(r'(?<=[.!?])\s+', text)
        
        # If that results in only one segment, use the whole text
        if len(sentences) <= 1:
            return [text.strip()]
        
        # Initialize variables for chunking
        chunks = []  # List to store final chunks
        current_chunk = []  # List to accumulate sentences for current chunk
        current_length = 0  # Word count for current chunk
        
        # Process each sentence
        for sentence in sentences:
            sentence = sentence.strip()  # Remove whitespace
            if not sentence:  # Skip empty sentences
                continue
            
            # Calculate word count for sentence
            word_count = len(sentence.split())
            
            # Check if adding this sentence would exceed chunk size
            if current_length + word_count > self.chunk_size and current_chunk:
                # Save current chunk
                chunk_text = ' '.join(current_chunk)  # Join sentences
                chunks.append(chunk_text)  # Add to chunks list
                
                # Start new chunk with overlap (last 1-2 sentences)
                if len(current_chunk) >= 2:
                    current_chunk = [current_chunk[-1], sentence]  # Keep last sentence for overlap
                else:
                    current_chunk = [sentence]  # Start new chunk with current sentence
                current_length = sum(len(s.split()) for s in current_chunk)  # Recalculate word count
            else:
                # Add sentence to current chunk
                current_chunk.append(sentence)
                current_length += word_count
        
        # Add any remaining chunk
        if current_chunk:
            chunk_text = ' '.join(current_chunk)
            chunks.append(chunk_text)
        
        # If no chunks were created, return original text
        if not chunks:
            return [text.strip()]
        
        return chunks  # Return list of chunks


# Main document processing pipeline class
class DocumentPipeline:
    """
    Complete document processing pipeline
    Orchestrates PDF/Excel processing and chunking
    """
    
    # Initialize pipeline with components
    def __init__(self, chunk_size: int = 512, overlap: int = 50, use_ocr: bool = True):
        self.pdf_processor = PDFProcessor(use_ocr=use_ocr)  # PDF processor
        self.excel_processor = ExcelProcessor()  # Excel processor
        self.chunker = DocumentChunker(chunk_size, overlap)  # Document chunker

    def _extract_text_and_tables_concurrent(
        self, pdf_path: str
    ) -> Tuple[List[Dict], List[Dict]]:
        """Run text extraction and table extraction concurrently for one PDF.

        They use independent libraries (PyMuPDF vs pdfplumber) and read the
        same file read-only, so they can overlap freely. Two threads is
        enough — table extraction itself fans out across processes internally,
        and text extraction is mostly waiting on disk + Tesseract subprocess.
        """
        with ThreadPoolExecutor(max_workers=2) as ex:
            text_future = ex.submit(self.pdf_processor.extract_text, pdf_path)
            tables_future = ex.submit(self.pdf_processor.extract_tables, pdf_path)
            try:
                pages = text_future.result()
            except Exception as e:  # noqa: BLE001
                logger.error(f"extract_text failed for {pdf_path}: {e}")
                pages = []
            try:
                tables = tables_future.result()
            except Exception as e:  # noqa: BLE001
                logger.error(f"extract_tables failed for {pdf_path}: {e}")
                tables = []
        return pages, tables

    # Method to process all documents in a directory
    def process_directory(self, directory: str) -> List[DocumentChunk]:
        """
        Process all documents in a directory with temporal extraction
        
        Args:
            directory: Path to directory containing documents
            
        Returns:
            List of processed document chunks with temporal metadata
        """
        dir_path = Path(directory)  # Convert to Path object
        all_chunks = []  # List to store all chunks from all files
        
        # Process PDF files
        for pdf_file in dir_path.glob("**/*.pdf"):  # Recursively find PDFs
            try:
                logger.info(f"Processing PDF: {pdf_file.name}")
                # Run text + table extraction concurrently (they're independent)
                pages, tables = self._extract_text_and_tables_concurrent(str(pdf_file))
                # Combine pages and tables
                file_documents = pages + tables
                
                # Chunk this file's documents with filename for temporal extraction
                file_chunks = self.chunker.chunk_documents(file_documents, doc_filename=pdf_file.name)
                all_chunks.extend(file_chunks)
            except Exception as e:
                logger.error(f"Failed to process {pdf_file}: {e}")  # Log error but continue
        
        # Process Excel files
        for excel_file in dir_path.glob("**/*.xlsx"):  # Recursively find Excel files
            try:
                logger.info(f"Processing Excel: {excel_file.name}")
                # Process Excel file
                sheets = self.excel_processor.process_excel(str(excel_file))
                # Chunk this file's sheets with filename
                file_chunks = self.chunker.chunk_documents(sheets, doc_filename=excel_file.name)
                all_chunks.extend(file_chunks)
            except Exception as e:
                logger.error(f"Failed to process {excel_file}: {e}")  # Log error but continue
        
        # Process CSV files
        for csv_file in dir_path.glob("**/*.csv"):  # Recursively find CSV files
            try:
                logger.info(f"Processing CSV: {csv_file.name}")
                # Read CSV file
                df = pd.read_csv(str(csv_file))
                # Create document dict
                csv_doc = [{
                    'text': df.to_string(),  # Convert DataFrame to string
                    'doc_name': csv_file.stem,  # File name without extension
                    'page_num': 0  # CSV doesn't have pages
                }]
                # Chunk with filename
                file_chunks = self.chunker.chunk_documents(csv_doc, doc_filename=csv_file.name)
                all_chunks.extend(file_chunks)
            except Exception as e:
                logger.error(f"Failed to process {csv_file}: {e}")  # Log error but continue
        
        # Log pipeline completion with temporal statistics
        temporal_chunks = sum(1 for c in all_chunks if c.temporal_entities and len(c.temporal_entities) > 0)
        chunks_with_validity = sum(1 for c in all_chunks if c.valid_from and c.valid_to)
        
        logger.info(f"✅ Pipeline complete: {len(all_chunks)} total chunks from {directory}")
        logger.info(f"   📅 {temporal_chunks} chunks with temporal entities")
        logger.info(f"   📅 {chunks_with_validity} chunks with validity periods")
        
        return all_chunks  # Return list of chunks
    
    # Method to process documents with multimodal support (text + images)
    def process_directory_multimodal(self, directory: str, extract_images: bool = True):
        """
        Process all documents in a directory with multimodal support.
        Returns both text chunks and image chunks separately.
        
        Args:
            directory: Path to directory containing documents
            extract_images: Whether to extract images from PDFs
            
        Returns:
            Tuple of (text_chunks: List[DocumentChunk], image_chunks: List[ImageChunk])
        """
        dir_path = Path(directory)
        all_documents = []  # Text content
        all_images = []  # Image content
        
        # Process PDF files
        for pdf_file in dir_path.glob("**/*.pdf"):
            try:
                # Run text + table extraction concurrently (they're independent)
                pages, tables = self._extract_text_and_tables_concurrent(str(pdf_file))
                all_documents.extend(pages)
                all_documents.extend(tables)
                
                # Extract images if enabled
                if extract_images:
                    images = self.pdf_processor.extract_images(str(pdf_file))
                    all_images.extend(images)
                    logger.info(f"Extracted {len(images)} images from {pdf_file.name}")
                    
            except Exception as e:
                logger.error(f"Failed to process {pdf_file}: {e}")
        
        # Process Excel files (no images)
        for excel_file in dir_path.glob("**/*.xlsx"):
            try:
                sheets = self.excel_processor.process_excel(str(excel_file))
                all_documents.extend(sheets)
            except Exception as e:
                logger.error(f"Failed to process {excel_file}: {e}")
        
        # Process CSV files (no images)
        for csv_file in dir_path.glob("**/*.csv"):
            try:
                df = pd.read_csv(str(csv_file))
                all_documents.append({
                    'text': df.to_string(),
                    'doc_name': csv_file.stem,
                    'page_num': 0
                })
            except Exception as e:
                logger.error(f"Failed to process {csv_file}: {e}")
        
        # Chunk text documents
        text_chunks = self.chunker.chunk_documents(all_documents)
        
        logger.info(f"Multimodal pipeline complete: {len(text_chunks)} text chunks, {len(all_images)} images")
        return text_chunks, all_images


# Example Usage
if __name__ == "__main__":
    # Initialize pipeline with parameters
    pipeline = DocumentPipeline(chunk_size=512, overlap=50, use_ocr=True)
    
    # Process documents in directory
    chunks = pipeline.process_directory("data/raw/pdfs")
    
    # Display sample chunks
    for chunk in chunks[:3]:  # Show first 3 chunks
        print(f"\n{chunk}")  # Print chunk metadata
        print(f"Content preview: {chunk.content[:200]}...")  # Print first 200 chars